// <auto-generated />
using System;
using AplicacaoCinema.WebApi.Infraestrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicacaoCinema.WebApi.Migrations
{
    [DbContext(typeof(CinemasDbContext))]
    [Migration("20220223230139_quinta-migracao")]
    partial class quintamigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplicacaoCinema.WebApi.Dominio.Filme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracao")
                        .HasColumnType("int")
                        .HasColumnName("Duracao");

                    b.Property<string>("Sinopse")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Sinopse");

                    b.Property<string>("Titulo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Filmes", "dbo");
                });

            modelBuilder.Entity("AplicacaoCinema.WebApi.Dominio.Ingresso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantidadeIngressos")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeIngressos");

                    b.Property<Guid>("SessaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessaoId");

                    b.ToTable("Ingressos", "dbo");
                });

            modelBuilder.Entity("AplicacaoCinema.WebApi.Dominio.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("DiaSemana");

                    b.Property<Guid>("FilmeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HorarioInicial")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("HorarioInicial");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(38,17)")
                        .HasColumnName("Preco");

                    b.Property<int>("TotalIngressos")
                        .HasColumnType("int")
                        .HasColumnName("TotalIngressos");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.ToTable("Sessoes", "dbo");
                });

            modelBuilder.Entity("AplicacaoCinema.WebApi.Dominio.Ingresso", b =>
                {
                    b.HasOne("AplicacaoCinema.WebApi.Dominio.Sessao", null)
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AplicacaoCinema.WebApi.Dominio.Sessao", b =>
                {
                    b.HasOne("AplicacaoCinema.WebApi.Dominio.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
